### ISSUE TITLE
How to use the models from huggingface?

### ISSUE THREAD

**Issue by nbalepur** [xuhaike/SparseCL#1]
Hello!

Do you have any code snippets on how to use your models uploaded to huggingface? Thanks!

**Comment by Rafa-zy** [comment]
Hi, thank you so much for reaching out! For now, you can directly download the repo by, e.g., 
`git lfs clone https://huggingface.co/SparseCL/GTE-SparseCL-hotpotqa `
make sure you have git-lfs installed by
`git lfs install`
And then you can change the model paths in the test scripts to run the inference.

In one week later, we will support our model in the huggingface format, and have a quick demo of how to use our sentence embedding model to derive embedding!

**Comment by nbalepur** [comment]
Got it, looking forward to it!
